select * from customer limit 20

-- total revenue generated by male vs female customers
select gender, sum(purchase_amount) as revenue
from customer
group by gender;

-- customers that used a discount but still spent above the average purchase amount
select customer_id, purchase_amount
from customer
where discount_applied = 'Yes' and purchase_amount >= (select avg(purchase_amount) from customer);

-- top 5 products with the highest average review rating
select item_purchased, round(avg(review_rating::numeric),2) as "average product rating"
from customer
group by item_purchased
order by avg(review_rating) desc
limit 5;

-- standard and express shipping avg purchase amounts
select shipping_type, round(avg(purchase_amount),2)
from customer 
where shipping_type in ('Standard','Express')
group by shipping_type;

-- subscribers and non-subscribers avg spend and total revenue
select subscription_status, count(customer_id) as total_customers, 
round(avg(purchase_amount),2) as avg_spend,
round(sum(purchase_amount),2) as total_revenue
from customer
group by subscription_status
order by total_revenue, avg_spend desc;

-- top 5 products having the highest purchase % with discounts applied
select item_purchased, 
round(100 * sum(case when discount_applied = 'Yes' then 1 else 0 end)/count(*),2) as discount_rate
from customer
group by item_purchased
order by discount_rate desc
limit 5;

-- segment customers based on total number of previous purchases and show count of each segment
with customer_type as (
select customer_id, previous_purchases, case
	when previous_purchases = 1 then 'New'
	when previous_purchases between 2 and 10 then 'Returning'
	else 'Loyal'
	end as customer_segment
from customer
)
select customer_segment, count(*) as "number of customers" 
from customer_type
group by customer_segment

-- top 3 most purchased products within each category
with item_counts as (
select category, item_purchased, count(customer_id) as total_orders, 
row_number() over(partition by category order by count(customer_id)desc) as item_rank
from customer
group by category, item_purchased
)
select item_rank, category, item_purchased, total_orders
from item_counts
where item_rank <= 3;

-- likeliness of a repeat buyer(> 5 previous purchases) subscribing
select subscription_status, count(customer_id) as repeat_buyers
from customer
where previous_purchases > 5
group by subscription_status;

-- revenue contribution by age group
select age_group, sum(purchase_amount) as total_revenue
from customer
group by age_group
order by total_revenue desc;